### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vipurkumar**
Adding etn.exohash.com in the new pools list.

### CODE REVIEW

**Comment by electroneumRepo** [comment]
@vipurkumar I just visited the url you have added as a pool and it appears the pool is down.

**Comment by agmardg** [comment]
Please add minig pool etn-pool.pl to pool list

**Comment by sitewizardgit** [comment]
@agmardg Please open your own pull request. Do not hook onto other peoples pull requests

**Comment by electroneumRepo** [comment]
@agmardg Please open your own pull request. Do not hook onto other peoples pull requests

**Comment by vipurkumar** [comment]
@electroneumRepo - Thanks for checking, pool node got stuck, restarted wallet rpc and pool node which fixed the problem. Can you please add now.

**Pull request merged**
